export type CertificationType = 'FSEC' | 'FSIC-Occupancy' | 'FSIC-Business';
export type ApplicationType = 'FSEC' | 'FSIC-Occupancy' | 'FSIC-Business';
export type BusinessStatus = 'New' | 'Renewal' | null;

export interface Establishment {
  id: string;
  name: string;
  dti_number: string;
  type: string;
  occupancy: string;
  storeys: string;
  floor_area: string;
  occupants: string;
  owner_first_name: string;
  owner_last_name: string;
  owner_middle_name: string | null;
  owner_suffix: string | null;
  owner_email: string;
  owner_mobile: string;
  owner_landline: string | null;
  rep_first_name: string | null;
  rep_last_name: string | null;
  rep_middle_name: string | null;
  rep_suffix: string | null;
  rep_email: string | null;
  rep_mobile: string | null;
  rep_landline: string | null;
  street: string;
  barangay: string;
  city: string;
  province: string;
  region: string;
  latitude: number | null;
  longitude: number | null;
  address: string;
}

export interface Application {
  application_id: string;
  id: string;
  submitted_at: string;
  type: CertificationType;
  business_status: BusinessStatus;
  status: string;
  establishment_id: string;
  owner_id: string;
  dti_number: string;
  owner_first_name: string;
  owner_last_name: string;
  owner_middle_name: string | null;
  owner_suffix: string | null;
  owner_email: string;
  owner_mobile: string;
  owner_landline: string | null;
  rep_first_name: string | null;
  rep_last_name: string | null;
  rep_middle_name: string | null;
  rep_suffix: string | null;
  rep_email: string | null;
  rep_mobile: string | null;
  rep_landline: string | null;
  street: string;
  barangay: string;
  city: string;
  province: string;
  region: string;
  latitude: number | null;
  longitude: number | null;
  contractor_name: string | null;
  fsec_number: string | null;
  occupancy_permit_no: string | null;
  created_at: string;
  updated_at: string;
  certificate_url: string | null;
  rejection_reasons: string[];
  rejection_notes: string | null;
  ownerName: string;
  establishments: Establishment;
  profiles?: {
    first_name: string;
    last_name: string;
    middle_name?: string | null;
    suffix?: string | null;
  } | null;
  architectural_documents?: string | null;
  civil_structural_documents?: string | null;
  mechanical_documents?: string | null;
  electrical_documents?: string | null;
  plumbing_documents?: string | null;
  sanitary_documents?: string | null;
  fire_protection_documents?: string | null;
  electronics_documents?: string | null;
  fire_safety_compliance_report?: string | null;
  cost_estimates_signed_sealed?: string | null;
  notarized_cost_estimates?: string | null;
  endorsement_obo?: string | null;
  certificate_of_completion?: string | null;
  assessment_fee_occupancy?: string | null;
  as_built_plan?: string | null;
  fire_safety_compliance_commissioning_report?: string | null;
  fire_safety_evaluation_clearance?: string | null;
  certificate_of_occupancy?: string | null;
  affidavit_no_substantial_changes?: string | null;
  business_permit_fee_assessment_new?: string | null;
  fire_insurance_new?: string | null;
  business_permit_fee_assessment_renewal?: string | null;
  fire_safety_maintenance_report?: string | null;
  fire_insurance_renewal?: string | null;
  fire_safety_clearance_hot_work?: string | null;
}