
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Supabase configuration
const SUPABASE_URL = "https://qthazonzfxhpcfqdflwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0aGF6b256ZnhocGNmcWRmbHdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwODE4OTgsImV4cCI6MjA1NzY1Nzg5OH0.KyayYgwSUUxdq3wwoxuXZqIyF6K8AL9jByKZSmM1z-Q";

/**
 * Create the Supabase client.
 * 
 * This client provides:
 * - Database access via `.from()` method
 * - Authentication via `.auth` methods
 * - Storage via `.storage` methods
 * - Functions via `.functions` methods
 */
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Database tables:
// - applications: For storing FSEC, FSIC-Business, and FSIC-Occupancy applications
// - establishments: For storing business establishments
// - events: For calendar events related to inspections and deadlines
// - inspections: For tracking inspection status and scheduling
// - notifications: For system notifications
// - profiles: For user profiles including inspectors, owners, and admins
// - inspection_checklists: For storing inspection checklist data and images

// Example usage:
// const { data, error } = await supabase.from('tableName').select('*')
